# cargo-deny policy for Arslan Hands' own helper (0.1.53). Same shape as the
# pinned agent-desktop's deny.toml: crates.io only, permissive licenses, no
# yanked crates, advisories checked.
[advisories]
version = 2
yanked = "deny"

[licenses]
version = 2
confidence-threshold = 0.8
allow = ["Apache-2.0", "MIT", "Unicode-3.0", "Unlicense"]

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
