const baseMessages = {
  en: { title: "Checks and deliverables", intro: "Parsing confirms structure, not visual quality or factual correctness. Unperformed checks stay visible.", passed: "Passed", failed: "Failed", not_run: "Not run", not_applicable: "Not applicable", unverified: "Not verified", deterministic: "Automatic check", human: "Your review", model: "Model assessment", artifacts: "Deliverables", open: "Open saved file", failedReason: "Some checks failed. Review the evidence and remaining work before continuing.", changedReason: "A saved file changed or is no longer available. Check it again before accepting.", details: "Technical check details" },
  zh: { title: "检查与交付物", intro: "解析通过只说明文件结构可读取，不代表视觉质量或事实正确。未执行的检查也会列出。", passed: "通过", failed: "未通过", not_run: "未执行", not_applicable: "不适用", unverified: "未验证", deterministic: "自动检查", human: "由你确认", model: "模型评估", artifacts: "交付物", open: "打开已保存文件", failedReason: "部分检查未通过。请先查看证据与未完成事项，再决定是否继续。", changedReason: "已保存文件发生变化或无法找到，请重新检查后再验收。", details: "检查技术详情" },
  ja: { title: "検証と成果物", intro: "解析は構造の確認であり、見た目や事実の正しさの保証ではありません。未実施の検証も表示します。", passed: "合格", failed: "不合格", not_run: "未実施", not_applicable: "対象外", unverified: "未検証", deterministic: "自動検証", human: "あなたの確認", model: "モデル評価", artifacts: "成果物", open: "保存したファイルを開く", failedReason: "一部の検証に失敗しました。続行前に証拠と残りの作業を確認してください。", changedReason: "保存したファイルが変更されたか見つかりません。承認前に再確認してください。", details: "検証の技術的詳細" },
  es: { title: "Comprobaciones y entregables", intro: "El análisis confirma la estructura, no la calidad visual ni la exactitud. Las comprobaciones no realizadas siguen visibles.", passed: "Aprobada", failed: "Fallida", not_run: "No realizada", not_applicable: "No aplicable", unverified: "Sin verificar", deterministic: "Comprobación automática", human: "Tu revisión", model: "Evaluación del modelo", artifacts: "Entregables", open: "Abrir archivo guardado", failedReason: "Algunas comprobaciones fallaron. Revisa las pruebas y el trabajo pendiente antes de continuar.", changedReason: "Un archivo guardado cambió o ya no está disponible. Revísalo antes de aceptar.", details: "Detalles técnicos" },
  de: { title: "Prüfungen und Ergebnisse", intro: "Die Analyse bestätigt die Struktur, nicht die visuelle Qualität oder sachliche Richtigkeit. Nicht ausgeführte Prüfungen bleiben sichtbar.", passed: "Bestanden", failed: "Fehlgeschlagen", not_run: "Nicht ausgeführt", not_applicable: "Nicht anwendbar", unverified: "Nicht geprüft", deterministic: "Automatische Prüfung", human: "Deine Prüfung", model: "Modellbewertung", artifacts: "Ergebnisse", open: "Gespeicherte Datei öffnen", failedReason: "Einige Prüfungen sind fehlgeschlagen. Prüfe Belege und offene Arbeit vor dem Fortsetzen.", changedReason: "Eine gespeicherte Datei wurde geändert oder ist nicht mehr verfügbar. Bitte vor der Abnahme erneut prüfen.", details: "Technische Prüfdetails" },
  fr: { title: "Vérifications et livrables", intro: "L’analyse confirme la structure, pas la qualité visuelle ni l’exactitude. Les vérifications non effectuées restent visibles.", passed: "Réussie", failed: "Échouée", not_run: "Non effectuée", not_applicable: "Sans objet", unverified: "Non vérifiée", deterministic: "Vérification automatique", human: "Votre vérification", model: "Évaluation du modèle", artifacts: "Livrables", open: "Ouvrir le fichier enregistré", failedReason: "Certaines vérifications ont échoué. Consultez les preuves et le travail restant avant de continuer.", changedReason: "Un fichier enregistré a changé ou n’est plus disponible. Vérifiez-le à nouveau avant d’accepter.", details: "Détails techniques" },
} as const;

const stateMessages = {
  en: { ...baseMessages.en, notRunReason: "Required checks have not run. Review the missing verifier or evidence before continuing; this result is not accepted." },
  zh: { ...baseMessages.zh, notRunReason: "必要检查尚未执行。请先查看缺少的验证器或证据，再决定是否继续；本次结果尚未验收。" },
  ja: { ...baseMessages.ja, notRunReason: "必要な検証が未実施です。続行前に不足する検証機能や証拠を確認してください。結果は未承認です。" },
  es: { ...baseMessages.es, notRunReason: "Faltan comprobaciones necesarias. Revisa el verificador o las pruebas que faltan antes de continuar; el resultado no está aceptado." },
  de: { ...baseMessages.de, notRunReason: "Erforderliche Prüfungen wurden nicht ausgeführt. Prüfe fehlende Prüffunktionen oder Belege vor dem Fortsetzen; das Ergebnis ist nicht abgenommen." },
  fr: { ...baseMessages.fr, notRunReason: "Des vérifications requises n’ont pas été effectuées. Consultez les outils ou preuves manquants avant de continuer ; le résultat n’est pas accepté." },
} as const;

export const validationMessages = {
  en: { ...stateMessages.en, unknownFile: "Unverified file", superseded: "Replaced by a newer version" },
  zh: { ...stateMessages.zh, unknownFile: "未验证文件", superseded: "已由新版本替换" },
  ja: { ...stateMessages.ja, unknownFile: "未検証のファイル", superseded: "新しい版に置き換え済み" },
  es: { ...stateMessages.es, unknownFile: "Archivo sin verificar", superseded: "Sustituido por una versión nueva" },
  de: { ...stateMessages.de, unknownFile: "Nicht geprüfte Datei", superseded: "Durch eine neuere Version ersetzt" },
  fr: { ...stateMessages.fr, unknownFile: "Fichier non vérifié", superseded: "Remplacé par une version plus récente" },
} as const;
